"""Create buses table

Revision ID: 50a58082b1c1
Revises: 152b8bd023ed
Create Date: 2025-05-05 14:52:31.216143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a58082b1c1'
down_revision = '152b8bd023ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buses')
    # ### end Alembic commands ###
